about_groups:
  default: ""
  type: list
  list_type: group

show_initial_members:
  default: 6
  type: integer

capitalize_names:
  default: true
  type: bool

order_additional_groups:
  default: "alphabetically"
  type: enum
  choices:
    - "alphabetically"
    - "order of creation"
    - "order of theme setting"

show_group_description:
  default: true
  type: bool
